name:                logical
version:             0.1.0.0
github:              "githubuser/logical"
license:             AllRightsReserved
author:              "Silvio Mayolo"
maintainer:          "mercerenies@comcast.net"
copyright:           "2020 Silvio Mayolo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/logical#readme>

dependencies:
- base >= 4.7 && < 5
- polysemy >= 1.3 && < 1.4
- polysemy-plugin >= 0.2.3 && < 0.3
- containers >= 0.5 && < 1
- parsec >= 3.1 && < 3.2

ghc-options:
- -O2
- -flate-specialise
- -fspecialize-aggressively
- -fplugin=Polysemy.Plugin
- -Wall
- -Wextra
- -Werror
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wcompat

default-extensions:
- DataKinds
- FlexibleContexts
- GADTs
- LambdaCase
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- TypeFamilies
- TemplateHaskell
- PatternSynonyms

library:
  source-dirs: src

executables:
  logical-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - logical

tests:
  logical-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - logical
    - HUnit >= 1 && < 2
